# name of the software
name: QuISL (Quantum Information Science Library)

project:
  version: 1.0.0
  download_url: https://github.com/quisl-framework/QuISL/releases
  download_text: Download

license:
  software: MIT License
  software_url: https://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/quisl-framework/QuISL
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/quisl-framework/QuISL
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/quisl-framework/QuISL
    - title: Issues
      icon: bug
      url: https://github.com/quisl-framework/QuISL/issues?state=open
  - title: Tweet
    icon: twitter
    brand: true
    url: https://twitter.com/intent/tweet?text=Check%20out%20the%20QuISL%20Framework%20https://quisl-framework.github.io/

ui:
  mode: 'auto' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: quisl-framework
    repo: QuISL
  twitter:
    enabled: true
    via:
    hash:
    account:
  facebook:
    enabled: true
    profileUrl:

analytics:
  google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png

theme: jekyll-docs-theme
remote_theme: allejo/jekyll-docs-theme@v1.0.0